info:
  description: API Documentation for Airbean API
  title: Airbean API
  version: 1.0.0
openapi: 3.0.1
components:
paths:
  # --------------- Menu ---------------
  /api/menu:
    # ----- GET menu items -----
    get:
      tags:
        - Menu
      description: Returns a menu of items
      responses:
        "200":
          description: Returns a menu of items
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: true
                  menu:
                    type: array
                    example:
                      [
                        {
                          prodId: prod-jespe,
                          title: Bryggkaffe,
                          desc: Bryggd på månadens bönor.,
                          price: 39,
                        },
                      ]

        "404":
          description: Failed to find menu
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: false
                  message:
                    type: string
                    example: Could not find any menu

    # ----- POST add new menu item -----
    post:
      tags:
        - Menu
      description:
      responses:
      requestBody:

  /api/menu/{prodId}:
    put:
      tags:
        - Menu
      description:
      responses:

    delete:
      tags:
        - Menu
      description:
      responses:

  # --------------- Auth ---------------
  /api/auth/logout:
    get:
      tags:
        - Auth
      description:
      responses:

  /api/auth/register:
    post:
      tags:
        - Auth
      description:
      responses:

  /api/auth/login:
    post:
      tags:
        - Auth
      description:
      responses:

  # --------------- Cart ---------------
  /api/cart:
    get:
      tags:
        - Cart
      description:
      responses:

    put:
      tags:
        - Cart
      description:
      responses:

  /api/cart/{cartId}:
    get:
      tags:
        - Cart
      description:
      responses:

  # --------------- Orders ---------------
  /api/orders:
    get:
      tags:
        - Orders
      description:
      responses:

    post:
      tags:
        - Orders
      description:
      responses:

  /api/orders/{userId}:
    get:
      tags:
        - Orders
      description:
      responses:
